### ISSUE TITLE
Can't [Read a Verb-Resource Permission]

### ISSUE THREAD

**Issue by hsakamoto123** [FIWARE/tutorials.Administrating-XACML#6]
You may need to make the same modifications as Update database seeding for Keyrock 8.2 or later. in "402. Roles and Permissions". 
Also apply to "406. Administrating XACML via a PAP".

container log：
{"log":"2022-12-19T10:19:13.333Z idm:api-permissions Error: SequelizeDatabaseError: Unknown column 'regex_entity_ids' in 'field list'\n","stream":"stderr","time":"2022-12-19T10:19:13.333596701Z"}

**Comment by jason-fox** [comment]
Fixed 8e06843

**Comment by hsakamoto123** [comment]
Fixed 8e06843：mysql-data/backup.sql

Three columns of `regex_entity_ids`, `regex_attributes`, `regex_types` have been added, but four columns of "INSERT INTO `permission` VALUES" have been added.
It seems that there is one extra ",", so please check.

After that, is it necessary to change "INSERT INTO `SequelizeMeta` VALUES"?

I want an answer to this question.

**Comment by jason-fox** [comment]
> After that, is it necessary to change "INSERT INTO SequelizeMeta VALUES"?

The tutorial is just pre-inserting some data into a MySQL. SequelizeMeta just reshapes an existing DB. It looks like the shape of some tables changed between 8.2 and 8.3.  You'll have to ask over a [Keyrock](https://github.com/ging/fiware-idm) how their Sequelize code has been set up.
